sonar.projectKey=PedroHCastelani_GameIdle
sonar.organization=pedro-castelani
sonar.projectName=GameIdle
sonar.sourceEncoding=UTF-8

sonar.sources=apps,packages,scripts
sonar.tests=apps,packages
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/.turbo/**,**/coverage/**,apps/api/prisma/migrations/**
sonar.coverage.exclusions=**/*.config.*,scripts/**,apps/api/prisma/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.cpd.exclusions=apps/api/prisma/migrations/**

sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info,apps/web/coverage/lcov.info,packages/shared/coverage/lcov.info
